<?php
declare(strict_types=1);

// -------------------------------------------------------------------------- //
// !!!!!!!!!!!!!!!!!!!!!!!!!! DO NOT EDIT THIS FILE !!!!!!!!!!!!!!!!!!!!!!!!! //
// -------------------------------------------------------------------------- //
//
// This file is should be exactly the same as the
// `Kickback\InitializationScripts\init.php` script,
// just declaring a different PARENT_PROCESS_TYPE variable.
//
// This file may be executed from within an incorrect script root,
// which introduces pitfalls for file inclusion (correct use of `require_once`)
// as well as pitfalls for version control and change management.
// Hence, it is best to just avoid editing this file, unless you must.
//
// As of this writing, the only foreseeable reason to edit this file would
// be if one is redesigning the init system for the entire Kickback namespace.
//
// If you just want to add initialization code, then it should probably
// be included from `Kickback\InitializationScripts\common_init.php`.
// That script will be executed from a more sane context: after changing script root.
//
// In addition to being important for allowing PHPStan to work,
// this file is also an example of how to note that initialization is
// NOT occuring in the ordinary web/cli context.
//
// See `change_root.php` for further explanation for why `init*.php`
// (and change_root.php) should not be edited and should be kept VERY simple.

// Communicate to the other startup scripts that we are running as part of PHPStan.
if (!defined('Kickback\InitializationScripts\PARENT_PROCESS_TYPE')) {
    define('Kickback\InitializationScripts\PARENT_PROCESS_TYPE', "PHPSTAN");
}

if (!defined('Kickback\PHPSTAN_RUNNING')) {
    define('Kickback\PHPSTAN_RUNNING', true);
}

// The change_root script will handle initialization from here.
// (It defines SCRIPT_ROOT and then calls the `common_init.php` in the correct SCRIPT_ROOT.)
require_once("change_root.php");

?>
