<?php
declare(strict_types=1);

// -------------------------------------------------------------------------- //
// !!!!!!!!!!!!!!!!!!!!!!!!!! DO NOT EDIT THIS FILE !!!!!!!!!!!!!!!!!!!!!!!!! //
// -------------------------------------------------------------------------- //
//
// This file may be executed from within an incorrect script root,
// which introduces pitfalls for file inclusion (correct use of `require_once`)
// as well as pitfalls for version control and change management.
// Hence, it is best to just avoid editing this file, unless you must.
//
// As of this writing, the only foreseeable reason to edit this file would
// be if one is redesigning the init system for the entire Kickback namespace.
//
// If you just want to add initialization code, then it should probably
// be included from `Kickback\InitializationScripts\common_init.php`.
// That script will be executed from a more sane context: after changing script root.
//
// If you need to add a special entry point, to indicate that we are not
// in the ordinary web/cli context, then use `Kickback\InitializationScripts\init_for_phpstan.php`
// as an example and keep it simple.
//
// See `change_root.php` for further explanation for why `init*.php`
// (and change_root.php) should not be edited and should be kept VERY simple.

// Communicate to the other startup scripts that we are running
// on a webserver ("WEB") or from a command line ("CLI").
if (!defined('Kickback\InitializationScripts\PARENT_PROCESS_TYPE')) {
    // @phpstan-ignore isset.variable, function.impossibleType, booleanAnd.alwaysTrue (Ignore "always set"|"never null"|"always true" errors, because they may only be true in the current environment.)
    if( isset($_SERVER) && (!is_null($_SERVER)) && !(0 === count($_SERVER))
    &&  array_key_exists("DOCUMENT_ROOT", $_SERVER) ) {
        define('Kickback\InitializationScripts\PARENT_PROCESS_TYPE', "WEB");
    } else {
        define('Kickback\InitializationScripts\PARENT_PROCESS_TYPE', "CLI");
    }
}

// The change_root script will handle initialization from here.
// (It defines SCRIPT_ROOT and then calls the `common_init.php` in the correct SCRIPT_ROOT.)
require_once("change_root.php");

?>
