<?php
declare(strict_types=1);

// -------------------------------------------------------------------------- //
// !!!!!!!!!!!!!!!!!!!!!!!!!! DO NOT EDIT THIS FILE !!!!!!!!!!!!!!!!!!!!!!!!! //
// -------------------------------------------------------------------------- //
//
// This file may be executed from within an incorrect script root,
// which introduces pitfalls for file inclusion (correct use of `require_once`)
// as well as pitfalls for version control and change management.
// Hence, it is best to just avoid editing this file, unless you must.
//
// As of this writing, the only foreseeable reason to edit this file would
// be if one is redesigning the init system for the entire Kickback namespace.
//
// If you just want to add initialization code, then it should probably
// be included from `Kickback\InitializationScripts\common_init.php`.
// That script will be executed from a more sane context: after changing script root.
//
// If you need to add a special entry point, to indicate that we are not
// in the ordinary web/cli context, then use `Kickback\InitializationScripts\init_for_phpstan.php`
// as an example and keep it simple.
//
// See `change_root.php` for further explanation for why `init*.php`
// (and change_root.php) should not be edited and should be kept VERY simple.

// Communicate to the other startup scripts that we are running
// on a webserver ("WEB") or from a command line ("CLI").
if (!defined('Kickback\InitializationScripts\PARENT_PROCESS_TYPE')) {
    // @phpstan-ignore isset.variable, function.impossibleType, booleanAnd.alwaysTrue (Ignore "always set"|"never null"|"always true" errors, because they may only be true in the current environment.)
    if( isset($_SERVER) && (!is_null($_SERVER)) && !(0 === count($_SERVER))
    &&  array_key_exists("DOCUMENT_ROOT", $_SERVER) ) {
        define('Kickback\InitializationScripts\PARENT_PROCESS_TYPE', "WEB");
    } else {
        define('Kickback\InitializationScripts\PARENT_PROCESS_TYPE', "CLI");
    }
}

// The change_root script will handle initialization from here.
// (It defines SCRIPT_ROOT and then calls the `common_init.php` in the correct SCRIPT_ROOT.)
require_once("change_root.php");

/*
....

// File that declares \Kickback\SCRIPT_ROOT.
// Do this first, so that we can use it to locate the correct script files.
require_once("script_root.php");

// Define some simple debug output and tracing mechanims that can be used
// in the autoloader, and (only!) in any other axiomatic initialization mechanisms.
require_once(\Kickback\SCRIPT_ROOT . "/Kickback/debug.php");

// Initialize+register the autoloader for \Kickback namespace classes,
// and for any classes that are manually managed with the project
// (ex: things in (\Kickback\SCRIPT_ROOT . "/vendor"))
require_once(\Kickback\SCRIPT_ROOT . "/Kickback/autoload_classes.php");

// Initialize+register composer's autoloader.
// We use `include_once` instead of `require_once` so that the site
// doesn't break if the admin hasn't made composer install anything yet.
// This is admissible because, as of this writing, any composer modules
// are optional dependencies, and most site functionality can work without them.
// Also seems to be important to wrap it in a "file_exists" if-statement
// because `include_once` can still generate HTML code (for displaying
// the warning) that may pollute the page (as seen by the user).
$kk_composer_autoloader_path = \Kickback\SCRIPT_ROOT . "/vendor/composer/autoload.php";
if ( file_exists($kk_composer_autoloader_path) ) {
    include_once($kk_composer_autoloader_path);
}
unset($kk_composer_autoloader_path);
*/
?>
